### PR TITLE
Source pages from the main branch on the tldr-pages/tldr repository instead of master

### PR DESCRIPTION
**Pull request by bl-ue**

### CODE REVIEW

**Comment by bl-ue** [comment]
@Techno-Disaster this repository ([Techno-Disaster/tldr-flutter](https://github.com/Techno-Disaster/tldr-flutter)) should rename the `master` branch to `main` — if you'd like, I can open a PR renaming references.

**Comment by Techno-Disaster** [comment]
> @Techno-Disaster this repository ([Techno-Disaster/tldr-flutter](https://github.com/Techno-Disaster/tldr-flutter)) should rename the `master` branch to `main` — if you'd like, I can open a PR renaming references.

I'll look into this getting data from tldr/main PR asap, but would like to keep the current tldr-flutter repo's default as master. I personally don't see any need for  changing from master to main. I'll look into keeping my default branch as main for future projects because that's what Github defaults to now.

**Comment by bl-ue** [comment]
>I'll look into this getting data from tldr/main PR asap

There's no need to — this PR does that already.

**Comment by Techno-Disaster** [comment]
> > I'll look into this getting data from tldr/main PR asap
> 
> There's no need to — this PR does that already 😉

Yep, merged it 👍 Thanks again for the contribution

**Pull request merged**
